apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: 80
        env:
        - name: secretCode
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: {{ .Values.secret.key }}
        - name: environment
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: {{ .Values.configMap.key }}
